### ISSUE TITLE
How to serialize the Pagerfanta instance

### ISSUE THREAD

**Issue by slince** [whiteoctober/WhiteOctoberPagerfantaBundle#165]
I have created an action with  fosrestbundle

```php
    /**
     * @Route("/users/{username}/followers.{_format}", name="user_followers", defaults={"_format"="html"})
     * @param string $username
     * @param Request $request
     * @return Response
     */
    public function getUserFollowersAction($username, Request $request)
    {
        $manager = $this->getUserManager();
        $user = $manager->findUserByName($username);
       
        $followers = $this->findUserFollowers($user, $request->query->getInt('page', 1));

        $view = $this->view($followers);
        $view->setTemplateVar('followers')
            ->setTemplate('PHPDishWebBundle:User:followers.html.twig');
        return $this->handleView($view);
    }

    /**
     * {@inheritdoc}
     */
    protected function findUserFollowers(UserInterface $user, $page, $limit = null)
    {
        $query = $this->getRepository()->createQueryBuilder('u')
            ->innerJoin('u.following', 'f')
            ->where('f.id = :userId')->setParameter('userId', $user->getId())
            ->getQuery();
        $paginator = new Pagerfanta(new DoctrineORMAdapter($query));
        $paginator->setCurrentPage($page);
        $paginator->setMaxPerPage($limit ?: $this->getMaxPerPage());
        return $paginator;
    }

```

If i visit "/users/bob/followers.json".  i will got e error liks this:

```json
{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "Resources are not supported in serialized data. Path: Monolog\\Handler\\StreamHandler -> Symfony\\Bridge\\Monolog\\Logger -> Symfony\\Component\\Cache\\Adapter\\FilesystemAdapter -> Symfony\\Component\\Cache\\Adapter\\TraceableAdapter -> Symfony\\Component\\Cache\\DoctrineProvider -> Doctrine\\Common\\Annotations\\CachedReader -> Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver -> Doctrine\\Common\\Persistence\\Mapping\\Driver\\MappingDriverChain -> Doctrine\\ORM\\Configuration -> Doctrine\\ORM\\EntityManager -> Doctrine\\ORM\\Query -> Doctrine\\ORM\\Tools\\Pagination\\Paginator -> Pagerfanta\\Adapter\\DoctrineORMAdapter -> Pagerfanta\\Pagerfanta",
        "class": "JMS\\Serializer\\Exception\\RuntimeException",
...
``

**Comment by sampart** [comment]
I've not had time to examine this one in depth, but I think the basic problem is that `$followers` is a `Pagerfanta` object, not a list of followers.  Can you change your template logic so that you pass in `$followers->getCurrentPageResults()` rather than just `$followers`?  `getCurrentPageResults` returns an array of the results, which should serialise better.

Hope this helps,
Sam

**Comment by slince** [comment]
@sampart  
Hi, I have tried like that; but i will got an empty result like:
```json
{}
```
Except: because i have to render a html page when client visits `/users/bob/followers.html`;  i cannot do like this in  a Practical  application

**Comment by imsheng** [comment]
+1 How to serialize the getCurrentPageResults() ?
or return array?

**Comment by slince** [comment]
@sampart   
Hi guys, Is there any solution?

**Comment by sampart** [comment]
It sounds like you're having two problems:
1) You're getting an empty result set from `getCurrentPageResults`
2) You want to pass the Pagerfanta itself to your template rather than the results, because the HTML version of the template (as opposed to the JSON) needs it (presumably for rendering your pagination links).

I can't help with (1) without seeing more code, but feel free to post more and I'll see what I can do.  I.e. what code gives this output?

(2) is more complicated - the question is whether you can pass in two parameters (the result set and Pagerfanta) but mark one of them as for the JSON view and one as for the HTML view (or something similar).  To find out whether this is possible, you'll need to look into the documentation for FOSRestBundle - that's outside the scope of this project itself.

**Comment by EneasVVA** [comment]
Just force casting doing:
 return (array)$pagerfanta->getCurrentPageResults()

**Comment by slince** [comment]
@EneasVVA  thanks

**Comment by ahmed-bhs** [comment]
You can use `iterator_to_array($paginatedCollection->getCurrentPageResults())` ;) instead of casting

**Comment by slince** [comment]
@ahmed-bhs tks

**Comment by JarJak** [comment]
Found this thread by Google so posting my solution here.

To serialize inside Twig template you can use this trick:
```twig
{{ pagerfanta | merge([]) | json_encode }}
```

Explanation:
Pagerfanta is an iterator instance which can't be simply serialized, but merge filter uses iterator_to_array internally.

**Comment by sampart** [comment]
Thanks for the tip, @JarJak.
